export const proyectos = [
  {
    id: 1,
    nombre: "Clone de Mercado Libre",
    tecnologia: "React, Redux, CSS, Bootstrap, Chakra-UI, Axios",
    desc: 'Clone de Mercado Libre consumiendo una API la cual trae los productos y son listados con sus características',
    img: "https://screenshot-proxy.netlify.app/f_avif,w_336/https://d33wubrfki0l68.cloudfront.net/624f1dc2baddda22aa2078bb/screenshot_2022-04-07-17-22-24-0000.png",
    pagina: "https://clone-mercadolibre-nabadia.vercel.app",
    repo: "https://github.com/NahuelAbadia/clone-mercadolibre",
  },
  {
    id: 2,
    nombre: "Clone de Netflix",
    tecnologia: "JavaScript, React, CSS, Axios",
    desc: "Clone de la UI de Netflix, consumiendo una API, listando peliculas y series por sus categorias",
    img: "https://screenshot-proxy.netlify.app/f_avif,w_336/https://d33wubrfki0l68.cloudfront.net/622aceb656d056559368bb00/screenshot_2022-03-11-04-23-24-0000.png",
    pagina: "https://netflix-clone-nabadia.netlify.app",
    repo: "https://github.com/NahuelAbadia/clone-netflix",
  },
  {
    id: 3,
    nombre: "Clone UI Twitter ",
    tecnologia: "JavaScript, React, Chakra-UI",
    desc: "Clone de la UI de Twitter con la funcionalidad de generar un tweet y poder borrar el mismo tocando encima de él",
    img: "https://d33wubrfki0l68.cloudfront.net/61e71152453787161146e8e7/screenshot_2022-01-18-19-13-27-0000.png",
    pagina: "https://clone-twitter-nabadia.netlify.app",
    repo: "https://github.com/NahuelAbadia/clone-twitter",
  },
  {
    id: 4,
    nombre: "Food App",
    tecnologia: "JavaScript, React, Redux, CSS, Bootstrap, Axios",
    desc: "Buscador de platos, con la funcionalidad de crear tu propio menu del dia con la API de Spoonacular",
    img: "https://screenshot-proxy.netlify.app/f_avif,w_336/https://d33wubrfki0l68.cloudfront.net/6261d2b99e43525e334e90de/screenshot_2022-04-21-21-55-16-0000.png",
    pagina: "https://food-app-nabadia.vercel.app",
    repo: "https://github.com/NahuelAbadia/food-app",
  },
  // {
  //   id: 3,
  //   nombre: "Cotizador de Criptomonedas",
  //   tecnologia: "JavaScript, React, Styled Components, Axios",
  //   desc: "Cotizador de criptomedas en tiempo real a traves de una API",
  //   img: "https://d33wubrfki0l68.cloudfront.net/61e717299307ef162d0aaa7b/screenshot_2022-01-18-19-38-22-0000.png",
  //   pagina: "https://cotizador-cripto-nabadia.netlify.app",
  //   repo: "https://github.com/NahuelAbadia/criptomonedas",
  // },
  // {
  //   id: 4,
  //   nombre: "Registro de turnos - Veterinaria",
  //   tecnologia: "JavaScript, React, CSS, Skeleton",
  //   desc: "CRUD para turnos de mascotas en una veterinaria",
  //   img: "https://d33wubrfki0l68.cloudfront.net/614a09c7831e9600b82d90f1/screenshot_2021-09-21-16-35-21-0000.png",
  //   pagina: "https://citas-app-nabadia.netlify.app",
  //   repo: "https://github.com/NahuelAbadia/citas",
  // },
]