import { FaHtml5, FaCss3Alt, FaGithub, FaGitAlt, FaReact, } from 'react-icons/fa'
import { SiJavascript, SiBootstrap, SiChakraui, SiFramer, SiRedux, SiTypescript, SiNextdotjs } from 'react-icons/si'

export const skills = [{
    id: 1,
    nombre: "HTML",
    color: "orange.500",
    logo: FaHtml5,
    link: "https://www.w3schools.com/html/",
},
{
    id: 2,
    nombre: "CSS",
    color: "#00A0E4",
    logo: FaCss3Alt,
    link: "https://www.w3schools.com/css/",
},
{
    id: 3,
    nombre: "Bootstrap",
    color: "purple.600",
    logo: SiBootstrap,
    link: "https://getbootstrap.com",
},
{
    id: 3,
    nombre: "JavaScript",
    color: "yellow.400",
    logo: SiJavascript,
    link: "https://www.javascript.com",
},
{
    id: 4,
    nombre: "React",
    color: "cyan.400",
    logo: FaReact,
    link: "https://reactjs.org",
},
{
    id: 5,
    nombre: "Redux",
    color: "violeta.100",
    logo: SiRedux,
    link: "https://redux.js.org",
},
{
    id: 6,
    nombre: "TypeScript",
    color: "blue.600",
    logo: SiTypescript,
    link: "https://www.typescriptlang.org",
},
{
    id: 7,
    nombre: "Next.js",
    color: "gris.100",
    logo: SiNextdotjs,
    link: "https://nextjs.org",
},
{
    id: 8,
    nombre: "Chakra-UI",
    color: "#44C7C0",
    logo: SiChakraui,
    link: "https://chakra-ui.com",
},
{
    id: 9,
    nombre: "Framer Motion",
    color: "negro.50",
    logo: SiFramer,
    link: "https://www.framer.com/motion/",
},
{
    id: 10,
    nombre: "Git",
    color: "orange.400",
    logo: FaGitAlt,
    link: "https://git-scm.com",
},
{
    id: 11,
    nombre: "GitHub",
    color: "whiteAlpha.800",
    logo: FaGithub,
    link: "https://github.com",
},
]